# Generated by Django 5.2 on 2025-04-23 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("descreption", models.TextField()),
                ("price", models.IntegerField()),
                ("stock", models.IntegerField()),
                ("category", models.CharField()),
                ("image", models.URLField(default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=None)),
            ],
        ),
    ]
