# Generated by Django 5.2 on 2025-04-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
