# Generated by Django 5.2.1 on 2025-06-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
    ]
