# Generated by Django 5.2.4 on 2025-07-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
