# Generated by Django 5.2.4 on 2025-07-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_stripe_id_product_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stripe_product_id',
        ),
    ]
