# Generated by Django 5.2.1 on 2025-07-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_image_delete_car_remove_product_image_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photo_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='descreption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
