# Generated by Django 5.2.1 on 2025-07-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_image_photo_url_alter_product_descreption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
