# Generated by Django 5.2 on 2025-04-30 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carts", "0019_remove_item_cart_cart_items"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrederList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_total", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("shipping_address", models.TextField(null=True)),
                ("order_notes", models.TextField(null=True)),
                (
                    "shipping_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("shipped", "shipped"),
                            ("delivered", "delivered"),
                        ],
                        default="pending",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash on delivery", "cash on delivery"),
                            ("visa", "visa"),
                        ],
                        default="cash on delivery",
                    ),
                ),
                ("items", models.ManyToManyField(to="carts.item")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
