# Generated by Django 5.2 on 2025-05-01 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0019_remove_item_cart_cart_items"),
        ("orders", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrederList",
            new_name="OrderList",
        ),
    ]
