# Generated by Django 5.2 on 2025-05-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0019_remove_item_cart_cart_items"),
        ("orders", "0002_rename_orederlist_orderlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderlist",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="items",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="order_notes",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="order_total",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="shipping_address",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="shipping_status",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="updated_at",
        ),
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_total", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("shipping_address", models.TextField(null=True)),
                ("order_notes", models.TextField(null=True)),
                (
                    "shipping_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("shipped", "shipped"),
                            ("delivered", "delivered"),
                        ],
                        default="pending",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash on delivery", "cash on delivery"),
                            ("visa", "visa"),
                        ],
                        default="cash on delivery",
                    ),
                ),
                ("items", models.ManyToManyField(to="carts.item")),
            ],
        ),
        migrations.AddField(
            model_name="orderlist",
            name="orders",
            field=models.ManyToManyField(to="orders.ordermodel"),
        ),
    ]
