# Generated by Django 5.2 on 2025-05-04 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0019_remove_item_cart_cart_items"),
        ("orders", "0003_remove_orderlist_created_at_remove_orderlist_items_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderModel",
            new_name="Order",
        ),
    ]
