# Generated by Django 5.2 on 2025-05-05 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_item"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order_Item",
        ),
    ]
