# Generated by Django 5.2 on 2025-05-05 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_delete_order_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="items",
            new_name="order_items",
        ),
    ]
