# Generated by Django 5.2 on 2025-05-05 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_rename_items_order_order_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_items",
            new_name="items",
        ),
    ]
