# Generated by Django 5.2 on 2025-05-05 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_rename_order_items_order_items"),
        ("products", "0002_alter_product_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order_Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("item_total", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(to="orders.order_item"),
        ),
    ]
