# Generated by Django 5.2 on 2025-05-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_item_alter_order_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cash on delivery", "cash on delivery"), (" ", "by card")],
                default="cash on delivery",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("shipped", "shipped"),
                    ("delivered", "delivered"),
                ],
                default="pending",
            ),
        ),
    ]
