# Generated by Django 5.2 on 2025-04-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="user_id",
            new_name="user",
        ),
    ]
