# Generated by Django 5.2 on 2025-04-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_rename_user_id_cart_user"),
        ("products", "0002_alter_product_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="items",
            field=models.ManyToManyField(to="products.product"),
        ),
    ]
