# Generated by Django 5.2 on 2025-04-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_cart_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total_items_price",
            field=models.IntegerField(default=0),
        ),
    ]
