# Generated by Django 5.2 on 2025-04-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0004_cart_total_items_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
