# Generated by Django 5.2 on 2025-04-28 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0006_item_alter_cart_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="cart_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="carts.cart"
            ),
        ),
    ]
