# Generated by Django 5.2 on 2025-04-28 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0007_item_cart_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="total_items_price",
            new_name="total_for_cart",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="items",
        ),
        migrations.RemoveField(
            model_name="item",
            name="cart_id",
        ),
        migrations.AddField(
            model_name="item",
            name="cart",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="carts.cart",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="total_for_item",
            field=models.IntegerField(default=0),
        ),
    ]
