# Generated by Django 5.2 on 2025-04-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0008_rename_total_items_price_cart_total_for_cart_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="total_for_cart",
            new_name="total_cart_amount",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="amount",
            new_name="quantity",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="total_for_item",
            new_name="total_item_amount",
        ),
    ]
