# Generated by Django 5.2 on 2025-04-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0009_rename_total_for_cart_cart_total_cart_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="cart",
        ),
        migrations.AddField(
            model_name="cart",
            name="items",
            field=models.ManyToManyField(to="carts.item"),
        ),
    ]
