# Generated by Django 5.2 on 2025-04-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0010_remove_item_cart_cart_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="total_cart_amount",
            new_name="cart_total",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="total_item_amount",
            new_name="item_total",
        ),
    ]
