# Generated by Django 5.2 on 2025-04-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0011_rename_total_cart_amount_cart_cart_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="items",
            field=models.ManyToManyField(null=True, to="carts.item"),
        ),
    ]
