# Generated by Django 5.2 on 2025-04-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0012_alter_cart_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="items",
        ),
    ]
