# Generated by Django 5.2 on 2025-04-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0013_remove_cart_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="items",
            field=models.ManyToManyField(null=True, to="carts.item"),
        ),
    ]
