# Generated by Django 5.2 on 2025-04-28 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0015_remove_cart_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="cart",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="carts.cart",
            ),
        ),
    ]
