# Generated by Django 5.2 on 2025-04-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0016_item_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="item",
            new_name="product_id",
        ),
    ]
