# Generated by Django 5.2 on 2025-04-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0017_rename_item_item_product_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="product_id",
            new_name="product",
        ),
    ]
