# Generated by Django 5.2 on 2025-04-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0018_rename_product_id_item_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="cart",
        ),
        migrations.AddField(
            model_name="cart",
            name="items",
            field=models.ManyToManyField(to="carts.item"),
        ),
    ]
