# Generated by Django 5.2 on 2025-05-04 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0019_remove_item_cart_cart_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="items",
        ),
        migrations.AddField(
            model_name="item",
            name="cart",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="carts.cart"
            ),
        ),
    ]
