# Generated by Django 5.2 on 2025-05-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0020_remove_cart_items_item_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="cart",
        ),
        migrations.AddField(
            model_name="cart",
            name="items",
            field=models.ManyToManyField(to="carts.item"),
        ),
    ]
