# Generated by Django 5.2 on 2025-05-21 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Init_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(choices=[('quick_link', 'quick_link'), ('invoice', 'invoice'), ('iframe', 'iframe')], default='iframe')),
                ('paymob_order_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='UNPAID')),
                ('payment_link_id', models.TextField()),
                ('checkout_link', models.TextField()),
                ('amount_cents', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('expiration', models.DateTimeField()),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transction_id', models.IntegerField()),
                ('paymob_order_id', models.IntegerField()),
                ('success', models.BooleanField()),
                ('api_source', models.CharField()),
                ('amount_cents', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
