# Generated by Django 5.2.4 on 2025-07-17 20:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_order_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Init_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_source', models.CharField(choices=[('quick_link', 'quick_link'), ('invoice', 'invoice'), ('iframe', 'iframe')], default='iframe')),
                ('paymob_order_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='UNPAID')),
                ('payment_link_id', models.TextField()),
                ('checkout_link', models.TextField()),
                ('amount_cents', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('expiration', models.DateTimeField()),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Stripe_checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_link', models.URLField()),
                ('amount', models.IntegerField()),
                ('stripe_checkout_id', models.CharField()),
                ('has_paid', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transction_id', models.IntegerField()),
                ('success', models.BooleanField()),
                ('amount_cents', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
