# Generated by Django 5.2.4 on 2025-07-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripe_checkout',
            name='payment_link',
            field=models.URLField(max_length=1000),
        ),
    ]
