# Generated by Django 5.2 on 2025-05-07 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_order_payment_method_and_more"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_link_id", models.IntegerField()),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("payment_status", models.CharField()),
                ("amount_cents", models.IntegerField()),
                ("checkout_url", models.URLField()),
                ("paymob_order_id", models.IntegerField()),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
