# Generated by Django 5.2 on 2025-05-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_order_payment_method_and_more"),
        ("payment", "0002_quicklink_delete_payment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QuickLink",
            new_name="QuickLinkPayment",
        ),
    ]
