# Generated by Django 5.2.4 on 2025-07-17 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_updated_at'),
        ('payment', '0003_alter_stripe_checkout_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripe_checkout',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
