# Generated by Django 5.2 on 2025-05-08 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_rename_quicklink_quicklinkpayment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quicklinkpayment",
            old_name="updated_at",
            new_name="expires_at",
        ),
    ]
