# Generated by Django 5.2 on 2025-05-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_rename_updated_at_quicklinkpayment_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quicklinkpayment",
            name="order_id",
            field=models.IntegerField(),
        ),
    ]
