# Generated by Django 5.2.4 on 2025-07-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_alter_stripe_checkout_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="amount_cents",
            new_name="amount",
        ),
        migrations.AddField(
            model_name="stripe_checkout",
            name="success_url",
            field=models.URLField(
                default="http://example.com/success", max_length=1000
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="provider",
            field=models.CharField(default="stripe"),
        ),
    ]
