# Generated by Django 5.2 on 2025-05-08 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_order_payment_method_and_more"),
        ("payment", "0005_alter_quicklinkpayment_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quicklinkpayment",
            name="order_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
    ]
