# Generated by Django 5.2.4 on 2025-07-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_amount_cents_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripe_checkout',
            name='success_url',
            field=models.URLField(default='http://example.com/success', max_length=1000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider',
            field=models.CharField(default='stripe'),
        ),
    ]
