# Generated by Django 5.2 on 2025-05-08 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_alter_quicklinkpayment_order_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quicklinkpayment",
            old_name="order_id",
            new_name="order",
        ),
    ]
