# Generated by Django 5.2 on 2025-05-08 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_order_payment_method_and_more"),
        ("payment", "0007_rename_order_id_quicklinkpayment_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Init_payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_source",
                    models.CharField(
                        choices=[
                            ("quick_link", "quick_link"),
                            ("invoice", "invoice"),
                            ("iframe", "iframe"),
                        ],
                        default="iframe",
                    ),
                ),
                ("payment_id", models.CharField()),
                ("amount_cents", models.IntegerField()),
                ("checkout_link", models.URLField()),
                ("created_at", models.DateTimeField()),
                ("expiration", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transction_id", models.IntegerField()),
                ("paymob_order_id", models.IntegerField()),
                ("success", models.BooleanField()),
                ("api_source", models.CharField()),
                ("created_at", models.DateTimeField()),
                ("amount_cents", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="QuickLinkPayment",
        ),
    ]
