# Generated by Django 5.2 on 2025-05-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0008_init_payment_transaction_delete_quicklinkpayment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="init_payment",
            old_name="payment_id",
            new_name="payment_link_id",
        ),
    ]
