# Generated by Django 5.2 on 2025-05-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0009_rename_payment_id_init_payment_payment_link_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="init_payment",
            name="payment_link_id",
            field=models.TextField(),
        ),
    ]
