# Generated by Django 5.2 on 2025-05-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0010_alter_init_payment_payment_link_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="init_payment",
            name="checkout_link",
            field=models.TextField(),
        ),
    ]
