# Generated by Django 5.2 on 2025-05-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0011_alter_init_payment_checkout_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="init_payment",
            name="status",
            field=models.CharField(default="UNPAID"),
        ),
    ]
