# Generated by Django 5.2 on 2025-05-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0012_init_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="init_payment",
            name="paymob_order_id",
            field=models.IntegerField(default=None),
        ),
    ]
