# Generated by Django 5.2 on 2025-05-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0014_alter_init_payment_paymob_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="init_payment",
            name="paymob_order_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
