# Generated by Django 5.2 on 2025-05-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0017_alter_init_payment_paymob_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="init_payment",
            name="paymob_order_id",
        ),
    ]
