# Generated by Django 5.2 on 2025-05-10 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_order_payment_method_and_more"),
        ("payment", "0019_init_payment_paymob_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="init_payment",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
        ),
    ]
