# Generated by Django 5.2 on 2025-05-10 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_order_payment_method_and_more"),
        ("payment", "0020_init_payment_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="init_payment",
            name="order",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
        ),
    ]
